#!/bin/sh
set -e

case "$1" in
    remove|upgrade|deconfigure)
        # Clean up cache directory
        rm -rf /var/cache/weather/*

        # Don't remove config file on upgrade
        if [ "$1" = "remove" ]; then
            rm -f /etc/asterisk/local/weather.ini
        fi
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0 