.TH SAYTIME.PL 1 "Saytime Weather" "" "Saytime Weather Manual"
.SH NAME
saytime.pl \- Announces the time and weather information
.SH SYNOPSIS
.B saytime.pl
[options]
.SH DESCRIPTION
saytime.pl announces the current time and weather conditions using pre-recorded audio files. It is designed for use with Asterisk and radio repeater controllers.
.SH OPTIONS
See the script or README for available options.
.SH AUTHOR
Jory A. Pratt <geekypenguin@gmail.com> 