.TH WEATHER.PL 1 "Saytime Weather" "" "Saytime Weather Manual"
.SH NAME
weather.pl \- Fetches and announces weather information
.SH SYNOPSIS
.B weather.pl
[location]
.SH DESCRIPTION
weather.pl fetches and announces current weather conditions and temperature using pre-recorded audio files. It is designed for use with Asterisk and radio repeater controllers.
.SH AUTHOR
Jory A. Pratt <geekypenguin@gmail.com> 